/*
* CONSTANTS
*
* Keywords - words that gg-bot will respond to - and other generic constants go
* here. If you want to debug gg-bot, make sure you replace the developer
* name with your own Discord username.
*
* Edit this file to customize what gg-bot will respond to when chatting.
*
*/

module.exports = Object.freeze({
  botName: 'haibara-san',
  commandFlag: '*',
  defaultRole: 'Student',
  developer: 'greenglasses',
  colours: {
    DEFAULT: 0,
    AQUA: 1752220,
    GREEN: 3066993,
    BLUE: 3447003,
    PURPLE: 10181046,
    GOLD: 15844367,
    ORANGE: 15105570,
    RED: 15158332,
    GREY: 9807270,
    DARKER_GREY: 8359053,
    NAVY: 3426654,
    DARK_AQUA: 1146986,
    DARK_GREEN: 2067276,
    DARK_BLUE: 2123412,
    DARK_PURPLE: 7419530,
    DARK_GOLD: 12745742,
    DARK_ORANGE: 11027200,
    DARK_RED: 10038562,
    DARK_GREY: 9936031,
    LIGHT_GREY: 12370112,
    DARK_NAVY: 2899536
  },
  compliments: [
    'a hottie',
    'adorable',
    'alluring',
    'amazing',
    'ambitious',
    'appealing',
    'attractive',
    'awesome',
    'beautiful',
    'best human',
    'best person',
    'brave',
    'breathtaking',
    'bright',
    'clever',
    'cool',
    'confident',
    'courteous',
    'cunning',
    'cute',
    'dedicated',
    'determined',
    'diligent',
    'enchanting',
    'enthralling',
    'fantastic',
    'fluffy',
    'good',
    'great',
    'handsome',
    'intelligent',
    'intriguing',
    'kawaii',
    'likeable',
    'loyal',
    'love',
    'nice',
    'perfect',
    'smart',
    'so smart',
    'so nice',
    'super',
    'the best',
    'the greatest',
    'tsundere'
  ],
  channels: {
    lounge: 'wr-chat',
    rules: 'welcome',
    welcome: 'welcome'
  },
  emojis: {
    happy: 'rumismiley',
    sad: 'rumiwhat'
  },
  goodbyes: [
    'bye',
    'goodbye',
    'au revoir',
    'sayonara',
    'see you',
    'see ya',
    'later'
  ],
  hellos: [
    'bonjour',
    ' yo!',
    'o/',
    "what's up",
    'hello',
    ' hi!',
    'hey',
    'konnichiwa',
    'morning',
    'evening',
    'afternoon'
  ],
  insults: [
    'an ass',
    'an idiot',
    'a b*tch',
    'a bitch',
    'a stubborn bitch',
    'a liar',
    'a loser',
    'a sucker',
    'annoying',
    'baka',
    'brainless',
    'crazy',
    'dumb',
    'foolish',
    'heartless',
    'horrible',
    'inferior',
    'infuriating',
    'mean',
    'ridiculous',
    'rude',
    'r00d',
    'stupid',
    'terrible',
    'uninteresting',
    'unlikeable'
  ],
  people: [
    'wakasa',
    'sensei',
    'rumi',
    'higo',
    'ryusuke',
    'akemi',
    'ran',,
    'mouri',
    'kisaki',
    'eri',
    'ayumi',
    'yoshida',
    'maria',
    'higashio',
    'sato',
    'miwako',
    'mary',
    'sera',
    'elena',
    'atsushi',
    'sumiko',
    'kobayashi',
    'yukiko',
    'naeko',
    'miike',
    'curacao',
    'mitsuhiko',
    'tsuburaya',
    'genta',
    'kojima',
    'shuukichi',
    'haneda',
    'meijin',
    'professor',
    'agasa',
    'jodie',
    'starling',
    'campbell',
    'fusae',
    'takagi',
    'wataru',
    'azusa',
    'enomoto',
    'megure',
    'juzou',
    'yonehara',
    'sakurako',
    'kazuha',
    'toyama'
  ],
  people1: [
    'subaru',
    'okiya',
    'kogoro',
    'kudo',
    'shinichi',
    'edogawa',
    'conan',
    'rye',
    'shiratori',
    'ninzaburo',
    'yumi',
    'miyamoto',
    'chiba',
    'kazunobu',
    'yamato',
    'kansuke',
    'uehara',
    'yui',
    'yamamura',
    'misao',
    'vodka',
    'heiji',
    'hattori',
    'gin',
    'vermouth',
    'moroboshi',
    'dai',
    'anokata',
    'boss',
    'karasuma',
    'renya',
    'pisco',
    'kid',
    'kaito',
    'sonoko',
    'suzuki',
    'yokomizo',
    'sango'
  ],
  nights: [
    'sleep',
    'night',
    'good night',
    'bed'
  ],
  warningTiers: {
    first: 15,
    second: 30,
    third: 40
  }
});
